name: Windows CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: call the other repo
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EVENT: push
        ORG: bibletime
        REPO: biblwtime-win
      run: |
        curl -d "{\"event_type\": \"${EVENT}\"}" -H "Content-Type: application/json" -H "Authorization: token ${GITHUB_TOKEN}" -H "Accept: application/vnd.github.everest-preview+json" "https://api.github.com/repos/${ORG}/${REPO}/dispatches"
